#!/bin/bash
set -e
set -x



mcdp-render \
    --stylesheet v_manual_screen \
    --maindir `dirname $1` \
    --mathjax 0 \
    --config_dirs `dirname $1` \
    --symbols docs/symbols.tex\
    --forgiving \
    "$1"
