#!/usr/bin/env python

import sys, os, re


def main():

    out = 'docs'
    figpath = os.path.dirname(os.path.realpath(__file__))
    inkscape_cmd = 'inkscape'
    latex_cmd = 'pdflatex'
    crop_cmd = 'pdfcrop'
    
    if not os.path.exists(figpath+'/'+out):
        print 'No directory' + figpath + '/' + out


    for(dirpath, dirnames, filenames) in os.walk(figpath+'/'+out):
        for filename in filenames:
            if (re.match( r'(.*).svg',filename)):
                # todo test if svg file is newer than existing pdf (if not no need to process)
                parts = filename.split('.')
                filename_pre = parts[0]
                pdf_tex_file = filename_pre+'_tmp.pdf_tex'
                pdf_tmp_file = filename_pre+'_tmp.pdf'
                pdffile = filename_pre+'.pdf'  # pdffile will be the same base as texfile since generated by pdflatex
                texfile = filename_pre+'.tex'
                svgfile = dirpath+'/'+filename_pre+'.svg'
                full_inkscape_cmd =  inkscape_cmd + ' -D -z --file='+svgfile+' --export-pdf='+pdf_tmp_file+' --export-latex' 
                os.system(full_inkscape_cmd)
                # ok now we have the pdf and pdf_tex files ready. Let's build the temp tex file to generate the figure

                f = open(texfile,'w')
                f.write(' \
                \documentclass[]{article} \n \
                \usepackage{graphicx} \n \
                \usepackage{color} \n \
                '+r'\b'+'egin{document} \n \
                \pagestyle{empty} \n \
                \input{'+pdf_tex_file+'} \n \
                \end{document}')
                f.close()
                full_latex_cmd = latex_cmd + ' ' + texfile
                os.system(full_latex_cmd)

                # ok now we have a pdf with just the image + the latex on it. last step is to crop

                full_crop_cmd = crop_cmd + ' ' + pdffile + ' ' + pdffile
                os.system(full_crop_cmd)

                #todo cleanup

            

if __name__ == '__main__':
    main()
