#!/usr/bin/env python

from image_ops_tester_generic import image_ops_tester_generic

image_ops_tester_generic(
	 forgot_to_check_empty=True, 
     forgot_to_check_truncated=False,
     forgot_to_check_not_existing=False,
     forgot_to_check_garbage=False,
)